### ISSUE TITLE
Clean run doesn't work off master

### ISSUE THREAD

**Issue by auser** [codechips/sapper-with-postcss-and-tailwind#3]
The commands I've run:

```bash
git clone https://github.com/codechips/sapper-with-postcss-and-tailwind.git template
cd template
npm install
npm run dev
```

The output:

```bash
❯ npm run dev


> TODO@0.0.1 dev /template
> run-p watch:*


> TODO@0.0.1 watch:dev /template
> sapper dev


> TODO@0.0.1 watch:css /template
> postcss src/assets/global.pcss -o static/global.css -w

✗ client
Cannot read property 'length' of undefined
✗ server
Cannot read property 'length' of undefined
internal/modules/cjs/loader.js:1033
  throw err;
  ^

Error: Cannot find module '/template/__sapper__/dev/server/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1030:15)
    at Function.Module._load (internal/modules/cjs/loader.js:899:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
> Server crashed
```

Any ideas where or why this might be happening?

**Comment by babichjacob** [comment]
See upstream https://github.com/sveltejs/svelte/issues/5722
(per the last comment, it should work to upgrade Svelte to 3.30.1)
